name: Student API CI Pipeline

on:
  workflow_dispatch:

  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'docker-compose.yml'
      - 'Makefile'

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Python
        run: |
          python3 --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --break-system-packages -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest

      - name: Run Code Linting
        run: |
          flake8 app/

      - name: Build Docker Image
        run: |
          docker build -t student-api:1.0.0 .

      - name: Verify Docker Image
        run: |
          docker images | grep student-api
